# Generated by Django 3.2.7 on 2021-09-30 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20210929_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='menulikes',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='menulikes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='menulikes',
            name='value',
        ),
        migrations.AddField(
            model_name='menulikes',
            name='likemenu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likemenu', to='api.menu'),
        ),
        migrations.AddField(
            model_name='menulikes',
            name='likeusers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
